# Generated by Django 5.1.5 on 2025-02-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('header_image', models.ImageField(blank=True, help_text='Custom header image for the flat page.', null=True, upload_to='flatpage_headers/')),
            ],
            options={
                'verbose_name': 'Custom Flat Page',
                'verbose_name_plural': 'Custom Flat Pages',
            },
            bases=('flatpages.flatpage',),
        ),
    ]
