# Generated by Django 3.2.10 on 2021-12-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_squashed_0009_alter_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='in_person_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
