# Generated by Django 2.2.12 on 2020-04-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200217_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDraft',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meetings.Topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='meetings.Topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('meetings.topic',),
        ),
    ]
