# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200217_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('repeat_meeting', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=3)),
                ('repeat_every', models.CharField(choices=[('first week', 'first week'), ('second week', 'second week'), ('third week', 'third week'), ('fourth week', 'fourth week'), ('last week', 'last week')], default='first week', max_length=12)),
                ('meeting_day_to_repeat', models.CharField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thur', 'Thur'), ('Fri', 'Fri'), ('Sat', 'Sat')], default='Mon', max_length=12)),
                ('meeting_time_to_repeat', models.TimeField()),
                ('repeat_meeting_starts', models.DateTimeField()),
                ('repeat_meeting_ends', models.DateTimeField()),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('live_stream', models.CharField(blank=True, max_length=500, null=True)),
                ('meetup_id', models.TextField(blank=True, null=True)),
                ('custom_title', models.CharField(blank=True, help_text="If you fill out this field, this 'custom_title'will show up as the title of the event.", max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('meeting_type', models.ForeignKey(blank=True, help_text='Type of meeting (i.e. SIG Meeting, Mentorship Meeting, Startup Row, etc.). Leave this empty for the main meeting. ', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingType')),
                ('where', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
