# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-18 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200217_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(blank=True, help_text='Type of meeting (i.e. SIG Meeting, Mentorship Meeting, Startup Row, etc.). Leave this empty for the main meeting. ', null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingType'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meetings.Venue'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='subgroup',
            field=models.ForeignKey(blank=True, help_text='Optional Sub-group (i.e. SIG)', null=True, on_delete=django.db.models.deletion.PROTECT, to='subgroups.SubGroup'),
        ),
        migrations.AlterField(
            model_name='presentor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text="Please select the meeting that you'd like to target your talk for.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='meetings.Meeting'),
        ),
    ]
