# Generated by Django 5.1.5 on 2025-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_rename_description2_meeting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
