# Generated by Django 2.2.13 on 2020-10-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200629_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='license',
            field=models.CharField(choices=[('CC 0', 'Creative Commons: No Rights Reserved'), ('CC BY', 'Creative Commons: Attribution'), ('CC BY-SA', 'Creative Commons: Attribution-ShareAlike'), ('CC BY-ND', 'Creative Commons: Attribution-NoDerivs'), ('CC BY-NC', 'Creative Commons: Attribution-NonCommercial'), ('CC BY-NC-SA', 'Creative Commons: Attribution-NonCommercial-ShareAlike'), ('CC BY-NC-ND', 'Creative Commons: Attribution-NonCommercial-NoDerivs'), ('All Rights Reserved', 'All Rights Reserved')], default='CC BY', max_length=50),
        ),
    ]
