# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_repeatmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatmeeting',
            name='registration_close_day_to_repeat',
            field=models.CharField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thur', 'Thur'), ('Fri', 'Fri'), ('Sat', 'Sat')], default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='repeatmeeting',
            name='registration_close_time_to_repeat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repeatmeeting',
            name='repeat_registration_close_date',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='repeatmeeting',
            name='repeat_every',
            field=models.CharField(choices=[('first week', 'first week of the month'), ('second week', 'second week of the month'), ('third week', 'third week of the month'), ('fourth week', 'fourth week the month'), ('last week', 'last week the month')], default='first week', max_length=12),
        ),
    ]
