# Generated by Django 4.2.9 on 2024-04-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_topic_requested_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('coordinating', 'coordinating'), ('confirmed', 'confirmed'), ('declined', 'declined'), ('failed', 'failed')], default='submitted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='live_stream',
            field=models.CharField(blank=True, help_text='url for livestream, no remote participants allowed if not present', max_length=500, null=True),
        ),
    ]
