# Generated by Django 2.2.13 on 2020-08-12 19:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200629_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text="Please select the meeting that you'd like to target your talk for.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topics', to='meetings.Meeting'),
        ),
        migrations.CreateModel(
            name='TopicDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='This will be the public title for your talk.', max_length=255)),
                ('experience_level', models.CharField(blank=True, choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, null=True, verbose_name='Audience Experience Level')),
                ('license', models.CharField(choices=[('CC BY', 'Creative Commons: Attribution'), ('CC BY-SA', 'Creative Commons: Attribution-ShareAlike'), ('CC BY-ND', 'Creative Commons: Attribution-NoDerivs'), ('CC BY-NC', 'Creative Commons: Attribution-NonCommercial'), ('CC BY-NC-SA', 'Creative Commons: Attribution-NonCommercial-ShareAlike'), ('CC BY-NC-ND', 'Creative Commons: Attribution-NonCommercial-NoDerivs'), ('All Rights Reserved', 'All Rights Reserved')], default='CC BY', max_length=50)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('embed_video', models.TextField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='This will be the public talk description.', null=True, verbose_name='Public Description')),
                ('notes', models.TextField(blank=True, help_text='Additional non-public information or context you want us to know about the talk submission.', null=True, verbose_name='Private Submission Notes')),
                ('slides_link', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(blank=True, help_text="Please select the meeting that you'd like to target your talk for.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicdrafts', related_query_name='topicdrafts', to='meetings.Meeting')),
                ('presentors', models.ManyToManyField(blank=True, to='meetings.Presentor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='meetings.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
