# Generated by Django 2.2.17 on 2021-01-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_add_cc0_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['-meeting', 'last_name', 'first_name'], 'verbose_name': 'RSVP'},
        ),
    ]
