# Generated by Django 4.2.11 on 2024-04-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_alter_topic_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="approved",
        ),
    ]
