# Generated by Django 2.2.17 on 2021-02-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20210110_1819'),
        ('meetings', '0005_auto_20201226_2020'),
    ]

    operations = [
    ]
