# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20200326_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatmeeting',
            name='meeting_day_to_repeat',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='repeatmeeting',
            name='registration_close_day_to_repeat',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=12),
        ),
        migrations.AlterField(
            model_name='repeatmeeting',
            name='repeat_meeting',
            field=models.CharField(choices=[('N', 'no'), ('Y', 'yes')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='repeatmeeting',
            name='repeat_registration_close_date',
            field=models.CharField(choices=[('N', 'no'), ('Y', 'yes')], default='N', max_length=1),
        ),
    ]
