# Generated by Django 4.2.11 on 2024-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_remove_topic_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="capacity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("draft", "draft"), ("published", "published")],
                default="submitted",
                max_length=50,
            ),
        ),
    ]
