# Generated by Django 2.2.17 on 2021-11-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_merge_20210214_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='in_person_capacity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='virtual_capacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for no maximum', null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('wait listed', 'wait listed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='response',
            field=models.CharField(choices=[('in-person', 'In-Person'), ('virtual', 'Virtually'), ('declined', 'Declined')], default='in-person', max_length=50),
        ),
    ]
