# Generated by Django 3.2.10 on 2021-12-13 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20211126_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='response',
            field=models.CharField(choices=[('in-person', 'in-person'), ('virtual', 'virtual'), ('declined', 'declined')], default='in-person', max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This will be the public talk description.', null=True),
        ),
    ]
