# Generated by Django 2.2.17 on 2021-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20211120_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='venue',
            field=models.CharField(choices=[('I', 'In Person'), ('V', 'Virtual')], default='I', max_length=1),
        ),
    ]
