# Generated by Django 5.1.3 on 2024-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_alter_meeting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="description2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
