# Generated by Django 2.2.17 on 2021-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20211120_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='response',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
