# Generated by Django 3.2.10 on 2021-12-15 14:36

import chipy_org.libs.custom_ckeditor
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20211213_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=chipy_org.libs.custom_ckeditor.CustomRichTextField(blank=True, help_text='This will be the public talk description.', null=True),
        ),
    ]
