# Generated by Django 5.1.3 on 2024-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_topic_description_data_to_description2"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="description2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingtype",
            name="description2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description2",
            field=models.TextField(
                blank=True, help_text="This will be the public talk description.", null=True
            ),
        ),
    ]
