# Generated by Django 2.2.17 on 2021-11-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20211120_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='venue',
            new_name='attendance_type',
        ),
    ]
