# Generated by Django 5.1.3 on 2024-11-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_announcement_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="text2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
