# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rsvp_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_external_recruiter',
            field=models.BooleanField(default=False, verbose_name='Are you an external recruiter?'),
        ),
    ]
