# Generated by Django 3.2.10 on 2022-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_userprofile_is_external_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short bio that will appear on organizer page'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email that will be displayed publicly'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_website',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Website that will be displayed publicly'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ORGANIZER', 'Organizer'), ('BOARD', 'Board Member'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('VICE_PRESIDENT', 'Vice President'), ('PRESIDENT', 'President')], default='MEMBER', max_length=16, verbose_name='Organizational role'),
        ),
    ]
