# Generated by Django 5.1.5 on 2025-03-21 15:31



from django.contrib.flatpages.models import FlatPage
from django.db import models

class CustomFlatPage(FlatPage):  # ✅ Extends FlatPage
    header_image = models.ImageField(upload_to="flatpage_headers/", blank=True, null=True)
    static_header_image = models.CharField(
        max_length=255, blank=True, null=True,
        help_text="Enter a static image path if not using an uploaded image."
    )

    def get_header_image_url(self):
        """Return the best available header image."""
        if self.header_image:
            return self.header_image.url
        if self.static_header_image:
            return f"/static/images/headers/{self.static_header_image}"
        return "/static/images/default-header.jpg"




iimport django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),  # Adjust this dependency if necessary
        ('profiles', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(
                    auto_created=True, 
                    on_delete=django.db.models.deletion.CASCADE, 
                    parent_link=True, 
                    primary_key=True, 
                    serialize=False, 
                    to='flatpages.flatpage'
                )),
                ('header_image', models.ImageField(upload_to="flatpage_headers/", blank=True, null=True)),
                ('static_header_image', models.CharField(
                    max_length=255, blank=True, null=True,
                    help_text="Enter a static image path if not using an uploaded image."
                )),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]


