# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-18 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20191021_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.SponsorGroup'),
        ),
    ]
