# Generated by Django 2.2.12 on 2020-04-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20191021_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name']},
        ),
    ]
