# Generated by Django 2.2.13 on 2020-11-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20200729_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSponsor',
        ),
    ]
