# Generated by Django 2.2.17 on 2021-01-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_delete_generalsponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorgroup',
            options={'ordering': ('list_priority',)},
        ),
    ]
