# Generated by Django 2.2.17 on 2021-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20210111_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorgroup',
            name='featured_sponsor_weight',
            field=models.IntegerField(default=1),
        ),
    ]
