# This defines a Persistent Volume Claim (PVC) for the ChiPy website
# that will be used to store static and uploaded media.
# A PVC is an applications request (claim) for some storage. 
# In this case, the Kind distribution has a "provisioner" which
# will see this PVC and automatically create a Persistent Volume (PV)
# that will satisfy this claim. The PV represents a block of 
# actual storage provisioned somewhere.
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Get the name of the pvc from an include from _helpers.tpl,
  # which will generate the name based on Helm chart name.
  name: {{ include "chipy-k8s.pvc" . }}
  # Include a standard set of labels from the _helpers.tpl
  labels:
    {{- include "chipy-k8s.labels" . | nindent 4 }}
spec:
  # This defines what "type" of storage to use. 
  # https://kubernetes.io/docs/concepts/storage/storage-classes/
  storageClassName: "{{ .Values.volumes.storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # defines how much storage to allocate
      storage: "{{ .Values.volumes.size }}"