apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chipy-k8s.secret" . }}
  labels:
    {{- include "chipy-k8s.labels" . | nindent 4 }}
stringData:
  SECRET_KEY: "{{ .Values.app.secret_key }}"
  GOOGLE_OAUTH2_CLIENT_ID: "{{ .Values.app.auth.google_oauth2_client_id }}"
  GOOGLE_OAUTH2_CLIENT_SECRET: "{{ .Values.app.auth.google_oauth2_client_secret }}"
  GITHUB_APP_ID: "{{ .Values.app.auth.github_app_id }}"
  GITHUB_API_SECRET: "{{ .Values.app.auth.github_api_secret }}"
  USE_S3: "{{ .Values.app.storage.use_s3 }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.app.storage.aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.app.storage.aws_secret_access_key }}"
  AWS_STORAGE_BUCKET_NAME: "{{ .Values.app.storage.aws_storage_bucket_name }}"
  NORECAPTCHA_SITE_KEY: "{{ .Values.app.captcha.norecaptcha_site_key }}"
  NORECAPTCHA_SECRET_KEY: "{{ .Values.app.captcha.norecaptcha_secret_key }}"
