# Set a k8s secret for secret creds in the ChiPy app
apiVersion: v1
kind: Secret
metadata:
  # Get the name of the secret from an include from _helpers.tpl,
  # which will generate the name based on Helm chart name.
  name: {{ include "chipy-k8s.secret" . }}
  # Include a standard set of labels from the _helpers.tpl
  labels:
    {{- include "chipy-k8s.labels" . | nindent 4 }}
stringData:
  # Set the secret data for this secret
  # Note: when this secret is viewed in-cluster, the
  # values will all be base64 encoded
  SECRET_KEY: "{{ .Values.app.secret_key }}"
  GOOGLE_OAUTH2_CLIENT_ID: "{{ .Values.app.auth.google_oauth2_client_id }}"
  GOOGLE_OAUTH2_CLIENT_SECRET: "{{ .Values.app.auth.google_oauth2_client_secret }}"
  GITHUB_APP_ID: "{{ .Values.app.auth.github_app_id }}"
  GITHUB_API_SECRET: "{{ .Values.app.auth.github_api_secret }}"
  USE_S3: "{{ .Values.app.storage.use_s3 }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.app.storage.aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.app.storage.aws_secret_access_key }}"
  AWS_STORAGE_BUCKET_NAME: "{{ .Values.app.storage.aws_storage_bucket_name }}"
  NORECAPTCHA_SITE_KEY: "{{ .Values.app.captcha.norecaptcha_site_key }}"
  NORECAPTCHA_SECRET_KEY: "{{ .Values.app.captcha.norecaptcha_secret_key }}"
