# This is a kubernetes system "user account" and will be assigned
# to pods in the ChiPy webserver and jobs. This is used to 
# restrict the what permissions those pods are allowed against
# the Kubernetes API. In this case, those pods do not need any
# permissions against the Kubernetes API (since the pods themselves
# are not creating k8s objects.)
{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  # Get the name of the sa from an include from _helpers.tpl,
  # which will generate the name based on Helm chart name.
  name: {{ include "chipy-k8s.serviceAccountName" . }}
  # Include a standard set of labels from the _helpers.tpl
  labels:
    {{- include "chipy-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # Allow users of this chart to specify annotations with
  # values.yaml files overrides. 
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
