# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-16 20:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='2500 Character Limit', max_length=2500)),
                ('is_sponsor', models.BooleanField(default=False, verbose_name='Is the company a sponsor of ChiPy?')),
                ('can_host_meeting', models.BooleanField(default=False, verbose_name='Is your organization interested in hosting an event?')),
                ('status', models.CharField(choices=[('SU', 'Submitted'), ('AP', 'Approved')], default='SU', max_length=2)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('days_to_expire', models.IntegerField(default=60, verbose_name='Num of days for post to show')),
                ('expiration_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('company_website', models.CharField(max_length=100)),
                ('agree_to_terms', models.BooleanField(verbose_name='I have read and agree to the referral terms, which includes giving a referral fee when a candidate is hired/placed.')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
