# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(max_length=2500),
        ),
    ]
