# Generated by Django 2.2.12 on 2020-07-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20200729_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_sponsor',
            field=models.BooleanField(default=False, verbose_name='Is the company a sponsor of ChiPy?'),
        ),
    ]
