# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_auto_20200409_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_verified_sponsor',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(help_text='2500 Character Limit', max_length=2500),
        ),
    ]
