# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_is_external_recruiter'),
        ('job_board', '0004_auto_20200412_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
