# Generated by Django 2.2.12 on 2020-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_auto_20200823_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.CharField(help_text="2500 Character Limit. Create a new paragraph by pressing 'Enter' twice.", max_length=2500),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='how_to_apply',
            field=models.CharField(help_text="2500 Character Limit. Create a new paragraph by pressing 'Enter' twice.", max_length=2500),
        ),
    ]
