# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_jobpost_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
