# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_auto_20200412_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
