# Generated by Django 2.2.12 on 2020-09-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0007_auto_20200823_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='status_change_date',
        ),
    ]
