# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0007_jobpost_agree_to_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name='Does the user agree to referral terms?'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsors.Sponsor', verbose_name='If your company is a sponsor of ChiPy, please select it from this list.'),
        ),
    ]
