# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_auto_20200413_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='agree_to_terms',
            field=models.BooleanField(verbose_name='Does the user agree to referral terms?'),
        ),
    ]
