# Generated by Django 2.2.13 on 2020-12-02 20:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_auto_20200901_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='time_to_expire',
            field=models.DurationField(default=datetime.timedelta(days=60), verbose_name='Num of days for post to show'),
        ),
    ]
