# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0009_auto_20200413_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_sponsor',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='is_verified_sponsor',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='link_to_company_page',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='approval_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_website',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='days_to_expire',
            field=models.IntegerField(default=30, verbose_name='Enter number of days you want post to show up'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='agree_to_terms',
            field=models.BooleanField(verbose_name='I have read and agree to the referral terms, which includes giving a referral fee when a candidate is hired/placed.'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitted'), ('AP', 'Approved')], default='SU', max_length=2),
        ),
    ]
