# Generated by Django 2.2.17 on 2020-12-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0010_job_post_copy_data_to_time_to_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='days_to_expire',
        ),
    ]
