# Generated by Django 3.2.10 on 2021-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0013_add_affiliates_squashed_0014_add_affiliates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='agree_to_terms',
            field=models.BooleanField(verbose_name='I have read and agree to the referral terms. Job posts are FREE for existing and new ChiPy sponsors. If you are not a ChiPy sponsor, each job post REQUIRES a $50 DONATION.'),
        ),
    ]
