# Generated by Django 5.1.5 on 2025-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0014_alter_jobpost_agree_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='filled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('SU', 'Submitted'), ('AP', 'Approved'), ('RE', 'Rejected'), ('NA', 'Filled')], default='SU', max_length=2),
        ),
    ]
