apiVersion: apps/v1
kind: Deployment
metadata:
  name: chipy-web
  labels:
    app: chipy-web
    componant: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chipy-webserver
  template:
    metadata:
      labels:
        app: chipy-webserver
    spec:
      serviceAccountName: chipy
      containers:
      - name: web
        image: chipy:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: chipy-static
          mountPath: /site/proj/staticfiles
        env:
        - name: DEBUG
          value: "True"
        - name: CONNECT_METHOD
          valueFrom:
            configMapKeyRef:
              name: chipy-webserver-config
              key: CONNECT_METHOD
        - name: SECURE_SSL_REDIRECT
          valueFrom:
            configMapKeyRef:
              name: chipy-webserver-config
              key: SECURE_SSL_REDIRECT
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: chipy-webserver-config
              key: ALLOWED_HOSTS
        - name: EMAIL_BACKEND
          valueFrom:
            configMapKeyRef:
              name: chipy-webserver-config
              key: EMAIL_BACKEND
        - name: ENVELOPE_EMAIL_RECIPIENTS
          valueFrom:
            configMapKeyRef:
              name: chipy-webserver-config
              key: ENVELOPE_EMAIL_RECIPIENTS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: DATABASE_URL
        - name: GOOGLE_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: GOOGLE_OAUTH2_CLIENT_ID
        - name: GOOGLE_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: GOOGLE_OAUTH2_CLIENT_SECRET
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: GITHUB_APP_ID
        - name: GITHUB_API_SECRET
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: GITHUB_API_SECRET
        - name: USE_S3
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: USE_S3
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: AWS_STORAGE_BUCKET_NAME
        - name: NORECAPTCHA_SITE_KEY
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: NORECAPTCHA_SITE_KEY
        - name: NORECAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chipy-webserver-secret
              key: NORECAPTCHA_SECRET_KEY
      volumes: 
      - name: chipy-static
        persistentVolumeClaim:
          claimName: chipy-web-static