apiVersion: batch/v1
kind: Job
metadata:
  name: chipy-collectstatic
spec:
  parallelism: 1
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: chipy
      containers:
      - name: collectstatic
        image: chipy:v1
        command: ["./manage.py",  "collectstatic", "--noinput"]
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: chipy.chipydb.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chipy.chipydb.credentials.postgresql.acid.zalan.do
              key: password
        - name: POSTGRES_HOST
          value: chipydb
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "chipy"
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: chipy-migrate
spec:
  parallelism: 1
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: chipy
      containers:
      - name: migrate
        image: chipy:v1
        command: ["./manage.py",  "migrate", "--noinput"]
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: chipy.chipydb.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chipy.chipydb.credentials.postgresql.acid.zalan.do
              key: password
        - name: POSTGRES_HOST
          value: chipydb
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "chipy"
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
      restartPolicy: Never


