apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chipy-web-static
  labels:
    # insert any desired labels to identify your claim
    app: test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
